// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: config/config.proto

package config

import (
	"context"
	"errors"

	"github.com/go-kratos/kratos/v2/log"
	"github.com/liujitcn/shop-base/server/api/gen/go/config"
	"github.com/liujitcn/shop-base/server/core"
	"github.com/liujitcn/shop-base/server/service/config/biz"
	"google.golang.org/grpc"
)

const _ = grpc.SupportPackageIsVersion7

// ConfigService is the server API for ConfigService service implement.
type ConfigService struct {
	config.UnimplementedConfigServiceServer
	*core.ShopCore
	configCase *biz.ConfigCase
}

// NewConfigService create a service implement.
// 系统配置公共服务
func NewConfigService(
	sc *core.ShopCore,
	configCase *biz.ConfigCase,
) *ConfigService {
	var ss = ConfigService{
		ShopCore:   sc,
		configCase: configCase}
	log.Debug("NewConfigService.")
	return &ss
}

// GetConfig
// 获取系统配置
func (s *ConfigService) GetConfig(ctx context.Context, req *config.ConfigRequest) (*config.ConfigResponse, error) {
	resp, err := s.configCase.GetConfig(ctx, req)
	if err != nil {
		log.Error("GetConfig err:", err.Error())
		return nil, errors.New("获取系统配置失败")
	}

	return resp, nil
}
