// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: login/login.proto

package login

import (
	"context"
	"errors"
	"time"

	"github.com/go-kratos/kratos/v2/log"
	"github.com/liujitcn/kratos-kit/auth"
	"github.com/liujitcn/kratos-kit/auth/authn/engine"
	"github.com/liujitcn/kratos-kit/captcha"
	"github.com/liujitcn/shop-base/server/api/gen/go/common"
	"github.com/liujitcn/shop-base/server/api/gen/go/login"
	"github.com/liujitcn/shop-base/server/core"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// LoginService is the server API for LoginService service implement.
type LoginService struct {
	login.UnimplementedLoginServiceServer
	*core.ShopCore
}

// NewLoginService create a service implement.
// 登录公共服务
func NewLoginService(
	sc *core.ShopCore,
) *LoginService {
	var ss = LoginService{
		ShopCore: sc,
	}

	// 设置验证码缓存
	captcha.SetStore(captcha.NewCacheStore(sc.Cache, 60*time.Second))

	log.Debug("NewLoginService.")
	return &ss
}

// Captcha
// 验证码
func (s *LoginService) Captcha(ctx context.Context, req *emptypb.Empty) (*login.CaptchaResponse, error) {
	id, b64s, _, err := captcha.DriverDigitFunc()
	if err != nil {
		return nil, err
	}
	return &login.CaptchaResponse{
		CaptchaId:     id,
		CaptchaBase64: b64s,
	}, err
}

// Logout
// 登出
func (s *LoginService) Logout(ctx context.Context, req *emptypb.Empty) (*emptypb.Empty, error) {
	authInfo, err := auth.FromContext(ctx)
	if err != nil {
		log.Errorf("用户认证失败[%s]", err.Error())
		return nil, common.ErrorAccessForbidden("用户认证失败")
	}
	err = s.UserToken.RemoveToken(authInfo.UserId)
	if err != nil {
		return nil, errors.New("退出登录失败")
	}
	return &emptypb.Empty{}, nil
}

// RefreshToken
// 刷新认证令牌
func (s *LoginService) RefreshToken(ctx context.Context, req *login.RefreshTokenRequest) (*login.LoginResponse, error) {
	authInfo, err := auth.FromContext(ctx)
	if err != nil {
		log.Errorf("用户认证失败[%s]", err.Error())
		return nil, common.ErrorAccessForbidden("用户认证失败")
	}

	// 校验刷新令牌
	refreshToken := s.UserToken.GetRefreshToken(authInfo.UserId)
	if refreshToken != req.GetRefreshToken() {
		return nil, common.ErrorIncorrectRefreshToken("invalid refresh token")
	}

	// 生成新的访问令牌
	var accessToken string
	accessToken, err = s.UserToken.GenerateAccessToken(authInfo)
	if err != nil {
		return nil, common.ErrorIncorrectRefreshToken("invalid refresh token")
	}
	// Token 有效期
	expiresIn := s.UserToken.GetAccessTokenExpires()

	return &login.LoginResponse{
		TokenType:    engine.BearerWord,
		AccessToken:  accessToken,
		RefreshToken: refreshToken,
		ExpiresIn:    expiresIn,
	}, nil
}
