// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: file/file.proto

package file

import (
	"context"
	"errors"

	"github.com/go-kratos/kratos/v2/log"
	"github.com/liujitcn/shop-base/server/api/gen/go/file"
	"github.com/liujitcn/shop-base/server/core"
	"github.com/liujitcn/shop-base/server/service/file/biz"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// FileService is the server API for FileService service implement.
type FileService struct {
	file.UnimplementedFileServiceServer
	*core.ShopCore
	fileCase *biz.FileCase
}

// NewFileService create a service implement.
// 文件服务
func NewFileService(
	sc *core.ShopCore,
	fileCase *biz.FileCase,
) *FileService {
	var ss = FileService{
		ShopCore: sc,
		fileCase: fileCase}
	log.Debug("NewFileService.")
	return &ss
}

// MultiUploadFile
// 多个文件上传
func (s *FileService) MultiUploadFile(ctx context.Context, req *file.MultiUploadFileRequest) (*file.MultiUploadFileResponse, error) {
	res, err := s.fileCase.MultiUploadFile(req)
	if err != nil {
		log.Error("MultiUploadFile err:", err.Error())
		return nil, errors.New("多个文件上传失败")
	}
	return res, nil
}

// UploadFile
// 单个文件上传
func (s *FileService) UploadFile(ctx context.Context, req *file.UploadFileInfo) (*file.FileInfo, error) {
	res, err := s.fileCase.UploadFile(req)
	if err != nil {
		log.Error("UploadFile err:", err.Error())
		return nil, errors.New("单个文件上传失败")
	}
	return res, nil
}

// DownloadFile
// 下载文件
func (s *FileService) DownloadFile(ctx context.Context, req *file.DownloadFileRequest) (*wrapperspb.BytesValue, error) {
	res, err := s.fileCase.DownloadFile(req)
	if err != nil {
		log.Error("DownloadFile err:", err.Error())
		return nil, errors.New("下载文件失败")
	}
	return res, nil
}
